# Generated by Django 5.0.7 on 2024-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_sites_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
